apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-producer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-producer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-producer
    spec:
      containers:
        - name: producer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKER
              value: {{ .Values.global.kafka.broker | default .Values.env.kafkaBroker | quote }}
            - name: KAFKA_TOPIC
              value: "trades-{{ .Values.global.coinSymbol | default .Values.env.coinSymbol }}"
            - name: COIN_SYMBOL
              value: {{ .Values.global.coinSymbol | default .Values.env.coinSymbol | quote }}
          envFrom:
            - secretRef:
                name: binance-api-keys 
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "cryptotrack"
        effect: "NoSchedule"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "app"
                operator: "In"
                values:
                - "cryptotrack"